modLoader = "javafml"
loaderVersion = "[42,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "findme"
version = "${version}"
displayName = "FindMe"
authors = "Buuz135"
description = '''
FindMe allows you to search for items in nearby inventories by pressing a key."
'''
#logoFile = ""

[[dependencies.findme]]
modId = "forge"
mandatory = true
versionRange = "[42,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.findme]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.findme]]
modId = "architectury"
mandatory = true
versionRange = "[2.3.23,)"
ordering = "AFTER"
side = "BOTH"