modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "findme"
version = "${version}"
displayName = "FindMe"
authors = "Buuz135"
description = '''
FindMe allows you to search for items in nearby inventories by pressing a key."
'''
#logoFile = ""
[[mixins]]
config = "findme-common.mixins.json"
[[dependencies.findme]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2.76,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.findme]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.findme]]
modId = "architectury"
type = "required"
versionRange = "[20.0.7,)"
ordering = "AFTER"
side = "BOTH"
