name: Publish action

on:
  create:
    tag:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: "17"
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: Publish Minecraft Mods Forge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 291936
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files-primary: forge/build/libs/*-forge.jar
          files-secondary: forge/build/libs/!(*-forge).jar
          version-type: beta
          loaders: forge
          game-versions: 1.20.1
          java: 17
          name: ""
          changelog: "https://github.com/Buuz135/FindMe/commits/1.19"
          dependencies: |
            architectury-api | depends | *
      - name: Publish Minecraft Mods Fabric
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          curseforge-id: 291936
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files-primary: fabric/build/libs/*-fabric.jar
          files-secondary: fabric/build/libs/!(*-fabric).jar
          version-type: beta
          loaders: fabric
          game-versions: 1.20.1
          java: 17
          name: ""
          dependencies: |
            architectury-api | depends | *
          changelog: "https://github.com/Buuz135/FindMe/commits/1.19"