name: Publish

on:
  create:
    tag:
      - '*'

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Set up Java 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "25"
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Publish NeoForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 291936
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-id: rEuzehyH
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: forge/build/libs/*-neoforge.jar
          name: FindMe ${{ github.ref_name }} for NeoForge
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: neoforge
          game-versions: 26.1.2
          java: 25
          dependencies: |
            architectury-api(required){modrinth:lhGA9TYQ}{curseforge:419699}

      - name: Publish Fabric
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 291936
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-id: rEuzehyH
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: fabric/build/libs/*-fabric.jar
          name: FindMe ${{ github.ref_name }} for Fabric
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: fabric
          game-versions: 26.1.2
          java: 25
          dependencies: |
            architectury-api(required){modrinth:lhGA9TYQ}{curseforge:419699}
            fabric-api(required){modrinth:P7dR8mSH}{curseforge:306612}
